name: Push Build to Artifactory

on: [ workflow_dispatch, push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }} 
        with:
          version: 2.61.0
          
      - name: Log in to Artifactory Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ARTIFACTORY_URL }} # Example: myartifactory.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}  # Your Artifactory username
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }} 
          
      - name: Build the Docker image
        run: | 
           docker build . --file Dockerfile --tag my-app:latest
           docker tag my-app:latest evidencetrial.jfrog.io/noam-docker-local/my-app:latest
      - name: Docker push
        run: |          
           docker push evidencetrial.jfrog.io/noam-docker-local/my-app:latest
   #        jf rt docker-push my-app:latest noam-docker-local --build-name=noam-docker --build-number=$GITHUB_RUN_NUMBER
      - name: Publish build info
        run: |          
             jf rt build-collect-env noam-docker $GITHUB_RUN_NUMBER
             jf rt build-publish noam-docker $GITHUB_RUN_NUMBER 
      - name: Log out from Artifactory
        if: always()
        run: docker logout ${{ vars.ARTIFACTORY_URL }}
        
          jf rt bdi c --max-builds=1
