name: Push Build to Artifactory

on: [push]

jobs:
 build:
   runs-on: ubuntu-latest
  
   steps:
   - name: Checkout Code
     uses: actions/checkout@v4

   - name: Setup JFrog CLI
     uses: jfrog/setup-jfrog-cli@v4
     env:
       JF_URL: ${{ vars.ARTIFACTORY_URL }}
       JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }} 

   - name: Run JFrog CLI
     run: |
       jf -v
       export SERVER_ID="test"
       jf rt ping

   - name: Push Build to Artifactory
     run: |
       echo "test file " > test.txt
       export BUILD_NAME="noam-github-actions-build"
       export BUILD_MODULE="my-module"
       export BUILD_NUMBER="1"


       export PATH_TO_DIRECTORY="name/version/dates"
      
       jf rt upload "test.txt" noam-generic-local

   # This action publishes the build information to Artifactory and deletes older builds
   - name: Build to Artifactory
     run: |
       export BUILD_NAME="noam-github-actions-build"
       export BUILD_MODULE="my-module"
       export BUILD_NUMBER="1"
       jf rt build-publish $BUILD_NAME $BUILD_NUMBER
     
       jf rt bdi c --max-builds=1
