name: Push Build to Artifactory

on: 
 push:
 repository_dispatch:
    types: hot-deploy

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Artifactory Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ARTIFACTORY_URL }} # Example: myartifactory.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}  # Your Artifactory username
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }} 
          
#      - name: Build the Docker image
#        run: | 
#           docker build . --file Dockerfile --tag my-app:latest
#           docker run my-app

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest


      - name: Log out from Artifactory
        if: always()
        run: docker logout ${{ vars.ARTIFACTORY_URL }}

