name: Push Build to Artifactory

on: 
 push:
 repository_dispatch:
    types: hot-deploy

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to Artifactory Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ARTIFACTORY_URL }} # Example: myartifactory.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}  # Your Artifactory username
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }} 
          
      - name: Build the Docker image
        run: | 
           docker build . --file Dockerfile --tag my-app:latest
           docker tag my-app:latest evidencetrial.jfrog.io/noam-docker-local/my-app:latest
           docker push evidencetrial.jfrog.io/noam-docker-local/my-app:latest

      - name: Log out from Artifactory
        if: always()
        run: docker logout ${{ vars.ARTIFACTORY_URL }}

      - name: Build to Artifactory
        run: |
          export BUILD_NAME="noam-github-actions-build"
          export BUILD_MODULE="my-module"
          export BUILD_NUMBER="1"
          export PATH_TO_DIRECTORY="name/version/dates"
          jf rt build-publish $BUILD_NAME $BUILD_NUMBER

        
          jf rt bdi c --max-builds=1
